[graph]
all-features = true

[advisories]
version = 2
ignore = [
]

[licenses]
version = 2
allow = [
  "0BSD",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MIT-0",
  "Unlicense",
  "Zlib",
]

exceptions = [
  { name = "unicode-ident", allow = [
    "Unicode-DFS-2016",
    "Unicode-3.0",
  ] },
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
# Certain crates that we don't want multiple versions of in the dependency tree
deny = [
  { name = "ahash", deny-multiple-versions = true },
  { name = "android-activity", deny-multiple-versions = true },
  { name = "glam", deny-multiple-versions = true },
  { name = "raw-window-handle", deny-multiple-versions = true },
]
skip = [
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/bevyengine/bevy"]

# thiserror is the preferred way to derive error types
[[bans.features]]
crate = "derive_more"
deny = ["error"]
